import {
  Transmission,
  Beds,
  CD,
  Freezer,
  Gas,
  Kitchen,
  MV,
  Toilet,
  Radio,
  TV,
  Shower,
  Hob,
  Water,
  Bathroom,
  Wind,
  Conditioner,
} from 'components/Icons';

export const iconDetails = {
  automatic: <Transmission />,
  airConditioner: <Conditioner />,
  AC: <Wind />,
  toilet: <Toilet />,
  CD: <CD />,
  TV: <TV />,
  kitchen: <Kitchen />,
  beds: <Beds />,
  radio: <Radio />,
  shower: <Shower />,
  freezer: <Freezer />,
  microwave: <MV />,
  gas: <Gas />,
  water: <Water />,
  hob: <Hob />,
  bathroom: <Bathroom />,
};
